import bcrypt from 'bcryptjs'

const data = {
  users: [
    {
      name: 'Liang',
      email: 'lwang@micro-wang.com',
      password: bcrypt.hashSync('1234567'),
      isAdmin: true,
    },
    {
      name: 'Asra',
      email: 'asra@mywhitecliffe.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'French Stick',
      slug: 'Bread-Bread-FrenchStick',
      image: '/images/frenchStick.webp',
      category: 'Bread',
      price: 4.27,
      description: 'French Stick',
      rating: 4.5,
      numReviews: 5,
      banner: '/images/frenchStick.webp',
    },
    {
      name: 'Ciabatta 550g',
      slug: 'Bread-Bread-Ciabatta550g',
      image: '/images/ciabatta550g.webp',
      category: 'Bread',
      price: 4.27,
      description: 'Ciabatta 550g',
      rating: 4.5,
      numReviews: 5,
      banner: '/images/ciabatta550g.webp',
    },
    {
      name: 'Ciabata 100g',
      slug: 'Bread-Bread-Ciabata100g',
      image: '/images/ciabata100g.jpg',
      category: 'Bread',
      price: 4.27,
      description: 'Ciabata 100g',
      rating: 4.5,
      numReviews: 5,
      banner: '/images/b11.png',
    },
    {
      name: 'Ciabata 300g',
      slug: 'Bread-Bread-Ciabata300g',
      image: '/images/ciabata300g.jpg',
      category: 'Bread',
      price: 4.27,
      description: 'Ciabata 300g',
      rating: 4.5,
      numReviews: 5,
      banner: '/images/ciabata300g.jpg',
    },
    {
      name: 'Banana Cake',
      slug: 'Pastry-Cream-BananaCake',
      image: '/images/cananaCake.jpg',
      category: 'Pastry',
      price: 4.27,
      description: 'Banana Cake',
      rating: 4.5,
      numReviews: 5,
      banner: '/images/b22.png',
    },
    {
      name: 'Apple Slice',
      slug: 'Pastry-Cream-AppleSlice',
      image: '/images/appleSlice.jpg',
      category: 'Pastry',
      price: 4.27,
      description: 'Apple Slice',
      rating: 4.5,
      numReviews: 5,
      banner: '/images/appleSlice.jpg',
    },
    {
      name: 'Fruit Pastry',
      slug: 'Pastry-Croissants-FruitPastry',
      image: '/images/fruitPastry.jpg',
      category: 'Pastry',
      price: 4.27,
      description: 'Fruit Pastry',
      rating: 4.5,
      numReviews: 5,
      banner: '/images/fruitPastry.jpg',
    },
    {
      name: 'Sable Biscuit',
      slug: 'Pastry-Biscuits-SableBiscuit',
      image: '/images/sableBiscuit.jpg',
      category: 'Pastry',
      price: 4.27,
      description: 'Sable Biscuit',
      rating: 4.5,
      numReviews: 5,
      banner: '/images/sableBiscuit.jpg',
    },
    {
      name: 'Donuts Plain',
      slug: 'Pastry-Biscuits-DonutsPlain',
      image: '/images/donutsPlain.jpg',
      category: 'Pastry',
      price: 4.27,
      description: 'Donuts Plain',
      rating: 4.5,
      numReviews: 5,
      banner: '/images/donutsPlain.jpg',
    },
    {
      name: 'Belgiunm Slice',
      slug: 'Pastry-CakesSlices-BelgiunmSlice',
      image: '/images/belgiunmSlice.jpg',
      category: 'Pastry',
      price: 4.27,
      description: 'Belgiunm Slice',
      rating: 4.5,
      numReviews: 5,
      banner: '/images/belgiunmSlice.jpg',
    },
    {
      name: 'Vienna Loaf',
      slug: 'Bread-Bread-ViennaLoaf',
      image: '/images/viennaLoaf.jpg',
      category: 'Bread',
      price: 4.27,
      description: 'Vienna Loaf',
      rating: 4.5,
      numReviews: 5,
      banner: '/images/viennaLoaf.jpg',
    },
    {
      name: 'Fruit Loaf',
      slug: 'Bread-Bread-FruitLoaf',
      image: '/images/fruitLoaf.jpg',
      category: 'Bread',
      price: 4.27,
      description: 'Fruit Loaf',
      rating: 4.5,
      numReviews: 5,
      banner: '/images/fruitLoaf.jpg',
    },
    {
      name: 'Filled Roll Chicken',
      slug: 'Sandwich-FilledBun-FilledRollChicken',
      image: '/images/filledRollChicken.png',
      category: 'Sandwich',
      price: 4.27,
      description: 'Filled Roll Chicken',
      rating: 4.5,
      numReviews: 5,
      banner: '/images/filledRollChicken.png',
    },
    {
      name: 'Filled Bap - Ham',
      slug: 'Sandwich-FilledBun-FilledBapHam',
      image: '/images/filledBapHam.jpg',
      category: 'Sandwich',
      price: 4.27,
      description: 'Filled Roll Chicken',
      rating: 4.5,
      numReviews: 5,
      banner: '/images/filledBapHam.jpg',
    },
    {
      name: 'Sandwich - Ham and Egg',
      slug: 'Sandwich-Sandwich-HamEgg',
      image: '/images/sandwichHamEgg.jpg',
      category: 'Sandwich',
      price: 4.27,
      description: 'Sandwich - Ham and Egg',
      rating: 4.5,
      numReviews: 5,
      banner: '/images/sandwichHamEgg.jpg',
    },
    {
      name: 'Sandwich - Ham and Tomato',
      slug: 'Sandwich-Sandwich-HamTomato',
      image: '/images/hamTomato.jpg',
      category: 'Sandwich',
      price: 4.27,
      description: 'Sandwich - Ham and Tomato',
      rating: 4.5,
      numReviews: 5,
      banner: '/images/b33.png',
    },
  ],
}

export default data
