import bcrypt from 'bcryptjs'

const data = {
  users: [
    {
      name: 'Liang',
      email: 'lwang@micro-wang.com',
      password: bcrypt.hashSync('1234567'),
      isAdmin: true,
    },
    {
      name: 'Asra',
      email: 'asra@mywhitecliffe.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'French Stick',
      slug: 'FrenchStick',
      image: '/images/frenchStick.webp',
      category: 'Bread',
      price: 2.99,
      description: 'Bread - French Stick',
      rating: 4.5,
      numReviews: 5,
      banner: '/images/frenchStick.webp',
    },
    {
      name: 'Ciabatta 550g',
      slug: 'Ciabatta550g',
      image: '/images/ciabatta550g.jpg',
      category: 'Bread',
      price: 4.59,
      description: 'Bread - Ciabatta 550g',
      rating: 4.5,
      numReviews: 5,
      banner: '/images/ciabatta550g.jpg',
    },
    {
      name: 'Ciabatta 100g',
      slug: 'Ciabatta100g',
      image: '/images/ciabatta100g.jpg',
      category: 'Bread',
      price: 1.79,
      description: 'Bread - Ciabatta 100g',
      rating: 4.5,
      numReviews: 5,
      banner: '/images/b11.png',
    },
    {
      name: 'Ciabatta 300g',
      slug: 'Ciabatta300g',
      image: '/images/ciabatta300g.jpg',
      category: 'Bread',
      price: 3.99,
      description: 'Bread - Ciabatta 300g',
      rating: 4.5,
      numReviews: 5,
      banner: '/images/ciabatta300g.jpg',
    },
    {
      name: 'Banana Cake',
      slug: 'BananaCake',
      image: '/images/cananaCake.jpg',
      category: 'Pastry',
      price: 6.99,
      description: 'Pastry - Banana Cake',
      rating: 4.5,
      numReviews: 5,
      banner: '/images/b22.png',
    },
    {
      name: 'Apple Slice',
      slug: 'AppleSlice',
      image: '/images/appleSlice.jpg',
      category: 'Pastry',
      price: 3.59,
      description: 'Pastry - Apple Slice',
      rating: 4.5,
      numReviews: 5,
      banner: '/images/appleSlice.jpg',
    },
    {
      name: 'Fruit Pastry',
      slug: 'FruitPastry',
      image: '/images/fruitPastry.jpg',
      category: 'Pastry',
      price: 3.59,
      description: 'Pastry - Fruit Pastry',
      rating: 4.5,
      numReviews: 5,
      banner: '/images/fruitPastry.jpg',
    },
    {
      name: 'Sable Biscuit',
      slug: 'SableBiscuit',
      image: '/images/sableBiscuit.jpg',
      category: 'Pastry',
      price: 3.59,
      description: 'Pastry - Sable Biscuit',
      rating: 4.5,
      numReviews: 5,
      banner: '/images/sableBiscuit.jpg',
    },
    {
      name: 'Donuts Plain',
      slug: 'DonutsPlain',
      image: '/images/donutsPlain.jpg',
      category: 'Pastry',
      price: 1.59,
      description: 'Pastry - Donuts Plain',
      rating: 4.5,
      numReviews: 5,
      banner: '/images/donutsPlain.jpg',
    },
    {
      name: 'Belgiunm Slice',
      slug: 'BelgiunmSlice',
      image: '/images/belgiunmSlice.jpg',
      category: 'Pastry',
      price: 2.99,
      description: 'Pastry - Belgiunm Slice',
      rating: 4.5,
      numReviews: 5,
      banner: '/images/belgiunmSlice.jpg',
    },
    {
      name: 'Vienna Loaf',
      slug: 'ViennaLoaf',
      image: '/images/viennaLoaf.jpg',
      category: 'Bread',
      price: 3.79,
      description: 'Bread - Vienna Loaf',
      rating: 4.5,
      numReviews: 5,
      banner: '/images/viennaLoaf.jpg',
    },
    {
      name: 'Fruit Loaf',
      slug: 'FruitLoaf',
      image: '/images/fruitLoaf.jpg',
      category: 'Bread',
      price: 3.79,
      description: 'Bread - Fruit Loaf',
      rating: 4.5,
      numReviews: 5,
      banner: '/images/fruitLoaf.jpg',
    },
    {
      name: 'Filled Roll Chicken',
      slug: 'FilledRollChicken',
      image: '/images/filledRollChicken.png',
      category: 'Sandwich',
      price: 2.99,
      description: 'Sandwich - Filled Roll Chicken',
      rating: 4.5,
      numReviews: 5,
      banner: '/images/filledRollChicken.png',
    },
    {
      name: 'Filled Bap - Ham',
      slug: 'FilledBapHam',
      image: '/images/filledBapHam.jpg',
      category: 'Sandwich',
      price: 4.99,
      description: 'Sandwich - Filled Roll Chicken',
      rating: 4.5,
      numReviews: 5,
      banner: '/images/filledBapHam.jpg',
    },
    {
      name: 'Sandwich - Ham and Egg',
      slug: 'HamEgg',
      image: '/images/sandwichHamEgg.jpg',
      category: 'Sandwich',
      price: 3.99,
      description: 'Sandwich - Ham and Egg',
      rating: 4.5,
      numReviews: 5,
      banner: '/images/sandwichHamEgg.jpg',
    },
    {
      name: 'Ham and Tomato',
      slug: 'HamTomato',
      image: '/images/hamTomato.jpg',
      category: 'Sandwich',
      price: 3.59,
      description: 'Sandwich - Ham and Tomato',
      rating: 4.5,
      numReviews: 5,
      banner: '/images/b33.png',
    },
  ],
}

export default data
